const state={lat:35.8256,lon:10.63699,lang:"ar"};let map,marker;
const $=id=>document.getElementById(id);
function text(v,ar,fr){return state.lang==="ar"?ar:fr}
function applyLang(){document.documentElement.lang=state.lang;document.documentElement.dir=state.lang==="ar"?"rtl":"ltr";document.querySelectorAll("[data-ar]").forEach(e=>e.textContent=e.dataset[state.lang==="ar"?"ar":"fr"]);$("langBtn").textContent=state.lang==="ar"?"FR":"AR"}
function fmtTime(v){return v?v.slice(11,16):"--:--"}
function weatherCode(c){const a={0:["صافي","Clear"],1:["غالبًا صافٍ","Mostly clear"],2:["غائم جزئيًا","Partly cloudy"],3:["غائم","Overcast"],61:["مطر","Rain"],63:["مطر","Rain"],65:["مطر غزير","Heavy rain"]};return a[c]||["حالة جوية","Weather"]}
async function loadWeather(){const w=await fetch(`https://api.open-meteo.com/v1/forecast?latitude=${state.lat}&longitude=${state.lon}&current=temperature_2m,relative_humidity_2m,pressure_msl,precipitation,wind_speed_10m,wind_gusts_10m,wind_direction_10m,weather_code&daily=sunrise,sunset&timezone=auto`).then(r=>r.json());$("temp").textContent=Math.round(w.current.temperature_2m)+"°C";$("wind").textContent=Math.round(w.current.wind_speed_10m)+" km/h";$("gust").textContent=(state.lang==="ar"?"هبات ":"Gusts ")+Math.round(w.current.wind_gusts_10m)+" km/h";$("winddir").textContent=Math.round(w.current.wind_direction_10m)+"°";$("rain").textContent=w.current.precipitation; $("pressure").textContent=Math.round(w.current.pressure_msl);const c=weatherCode(w.current.weather_code);$("condition").textContent=state.lang==="ar"?c[0]:c[1];$("sunrise").textContent=fmtTime(w.daily.sunrise[0]);$("sunset").textContent=fmtTime(w.daily.sunset[0])}
async function loadMarine(){const m=await fetch(`https://marine-api.open-meteo.com/v1/marine?latitude=${state.lat}&longitude=${state.lon}&current=wave_height,wave_direction,wave_period&timezone=auto`).then(r=>r.json());if(m.current){$("wave").textContent=Number(m.current.wave_height).toFixed(1)+" m";$("period").textContent=(state.lang==="ar"?"الفترة ":"Period ")+Number(m.current.wave_period).toFixed(1)+" s";$("wavedir").textContent=(state.lang==="ar"?"الموج ":"Wave ")+Math.round(m.current.wave_direction)+"°"}}
async function load(){ $("place").textContent=state.lat.toFixed(4)+", "+state.lon.toFixed(4);try{await Promise.all([loadWeather(),loadMarine()])}catch(e){$("place").textContent=text("","تعذر تحميل البيانات","Data unavailable")}}
function setLocation(lat,lon){state.lat=lat;state.lon=lon;if(marker)marker.setLatLng([lat,lon]);else marker=L.marker([lat,lon]).addTo(map);load()}
function init(){map=L.map("map",{zoomControl:false}).setView([state.lat,state.lon],8);L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{attribution:"© Esri"}).addTo(map);setLocation(state.lat,state.lon);map.on("click",e=>setLocation(e.latlng.lat,e.latlng.lng));$("gps").onclick=()=>navigator.geolocation?.getCurrentPosition(p=>setLocation(p.coords.latitude,p.coords.longitude));$("langBtn").onclick=()=>{state.lang=state.lang==="ar"?"fr":"ar";applyLang();load()};applyLang()}
init();