const map=L.map("map",{zoomControl:false,preferCanvas:true}).setView([35.8,10.7],7);
const street=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(map);
const sat=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{attribution:"© Esri"});
L.control.zoom({position:"bottomright"}).addTo(map);
const bathy=L.tileLayer.wms("https://wms.gebco.net/mapserv?",{layers:"gebco_latest_2",format:"image/png",transparent:true,version:"1.3.0",attribution:"Bathymetry © GEBCO"});
let mode="wind",marker=null,grid=[],beachLayer=L.layerGroup(),field=document.createElement("canvas"),fieldCtx=field.getContext("2d"),fieldLayer=document.createElement("div"),favorites=JSON.parse(localStorage.getItem("pkf-favorites")||"[]"),lang=localStorage.getItem("pkf-lang")||"ar";
const status=document.getElementById("status"),legend=document.getElementById("legend"),point=document.getElementById("point"),info=document.getElementById("info"),sheet=document.getElementById("sheet");
field.className="field-canvas";fieldLayer.className="field-canvas";map.getContainer().appendChild(field);field.style.pointerEvents="none";
function msg(s){status.textContent=s}
function t(ar,fr){return lang==="ar"?ar:fr}
function resizeField(){field.width=map.getSize().x*devicePixelRatio;field.height=map.getSize().y*devicePixelRatio;field.style.width=map.getSize().x+"px";field.style.height=map.getSize().y+"px";fieldCtx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);drawField()}
function valueColor(v,type){if(type==="waves")return v<.5?"#54ddff":v<1?"#26a9ff":v<1.5?"#ffd24b":"#ff554b";if(type==="current")return v<.15?"#57e7ff":v<.4?"#a36cff":"#ff5ac8";if(type==="sst")return v<18?"#5a78ff":v<22?"#55d9ff":v<26?"#ffe05b":"#ff684d";return v<10?"#52e39b":v<20?"#ffe05b":"#ff5a4f"}
let forecast=[],timeIndex=0,playing=false,playTimer=null,particles=[];
function currentGrid(){return forecast.map(q=>({lat:q.lat,lon:q.lon,wind:q.wind?.[timeIndex],dir:q.dir?.[timeIndex],wave:q.wave?.[timeIndex],cur:q.cur?.[timeIndex],cdir:q.cdir?.[timeIndex],sst:q.sst?.[timeIndex]}))}
function seedParticles(){particles=Array.from({length:220},(_,i)=>({x:(i*97)%Math.max(1,map.getSize().x),y:(i*53)%Math.max(1,map.getSize().y),life:Math.random()*80+20}))}
function nearestField(x,y){let best=null,bd=1e9;for(const q of grid){const p=map.latLngToContainerPoint([q.lat,q.lon]),d=(p.x-x)**2+(p.y-y)**2;if(d<bd){bd=d;best=q}}return best}
function drawWindParticles(){if(mode!=="wind"||!grid.length)return;fieldCtx.save();fieldCtx.globalCompositeOperation="lighter";for(const p of particles){const q=nearestField(p.x,p.y);if(!q||!Number.isFinite(q.wind)||!Number.isFinite(q.dir))continue;const ang=q.dir*Math.PI/180,spd=Math.max(0.35,Math.min(2.8,q.wind/12));p.x+=Math.sin(ang)*spd;p.y-=Math.cos(ang)*spd;p.life--;fieldCtx.globalAlpha=Math.max(.1,Math.min(.85,p.life/35));fieldCtx.fillStyle="#bdefff";fieldCtx.fillRect(p.x,p.y,2.2,2.2);if(p.life<=0||p.x<0||p.y<0||p.x>map.getSize().x||p.y>map.getSize().y){p.x=Math.random()*map.getSize().x;p.y=Math.random()*map.getSize().y;p.life=80+Math.random()*100}}fieldCtx.restore()}
function drawField(){fieldCtx.clearRect(0,0,map.getSize().x,map.getSize().y);if(!grid.length)return;const w=mode==="wind"?"wind":mode==="waves"?"wave":mode==="current"?"cur":"sst";const vals=grid.map(x=>x[w]).filter(Number.isFinite);if(!vals.length)return;const min=Math.min(...vals),max=Math.max(...vals)||min+1;const step=Math.max(24,Math.min(58,44*Math.pow(2,map.getZoom()-7)));for(const q of grid){const v=q[w];if(!Number.isFinite(v))continue;const p=map.latLngToContainerPoint([q.lat,q.lon]);const a=.16+.34*((v-min)/(max-min||1));fieldCtx.globalAlpha=a;fieldCtx.fillStyle=valueColor(v,mode);fieldCtx.beginPath();fieldCtx.arc(p.x,p.y,step*.48,0,Math.PI*2);fieldCtx.fill();if(mode==="wind"){const ang=(q.dir||0)*Math.PI/180,len=step*.7;fieldCtx.globalAlpha=.65;fieldCtx.strokeStyle="#effcff";fieldCtx.lineWidth=1.1;fieldCtx.beginPath();fieldCtx.moveTo(p.x,p.y);fieldCtx.lineTo(p.x+Math.sin(ang)*len,p.y-Math.cos(ang)*len);fieldCtx.stroke() }else if(mode==="current"){const ang=(q.cdir||0)*Math.PI/180,len=step*.45;fieldCtx.globalAlpha=.7;fieldCtx.strokeStyle="#fff";fieldCtx.beginPath();fieldCtx.moveTo(p.x,p.y);fieldCtx.lineTo(p.x+Math.sin(ang)*len,p.y-Math.cos(ang)*len);fieldCtx.stroke()}}fieldCtx.globalAlpha=1;if(mode==="wind")drawWindParticles()}
async function loadForecast(){try{msg(t("جاري تحميل توقعات البحر والرياح…","Chargement des prévisions mer et vent…"));const lats=[],lons=[];for(let lat=33.5;lat<=37.5;lat+=.5)for(let lon=7.5;lon<=11.5;lon+=.5){lats.push(lat.toFixed(2));lons.push(lon.toFixed(2))}const weather="https://api.open-meteo.com/v1/forecast?latitude="+lats.join(",")+"&longitude="+lons.join(",")+"&hourly=wind_speed_10m,wind_direction_10m&forecast_days=2&timezone=auto&cell_selection=sea";const marine="https://marine-api.open-meteo.com/v1/marine?latitude="+lats.join(",")+"&longitude="+lons.join(",")+"&hourly=wave_height,sea_surface_temperature,ocean_current_velocity,ocean_current_direction&forecast_days=2&timezone=auto&cell_selection=sea";const [wr,mr]=await Promise.all([fetch(weather).then(x=>x.json()),fetch(marine).then(x=>x.json())]);const wa=Array.isArray(wr)?wr:[wr],ma=Array.isArray(mr)?mr:[mr];forecast=ma.map((q,i)=>({lat:+lats[i],lon:+lons[i],wave:q.hourly?.wave_height||[],sst:q.hourly?.sea_surface_temperature||[],cur:q.hourly?.ocean_current_velocity||[],cdir:q.hourly?.ocean_current_direction||[],wind:wa[i]?.hourly?.wind_speed_10m||[],dir:wa[i]?.hourly?.wind_direction_10m||[],times:q.hourly?.time||wa[i]?.hourly?.time||[]})).filter(q=>q.times.length);const times=forecast[0]?.times||[];const target=document.getElementById("time");target.max=Math.max(0,Math.min(47,times.length-1));timeIndex=Math.min(timeIndex,+target.value||0);document.getElementById("timeLabel").textContent=formatTime(times[timeIndex]);grid=currentGrid();seedParticles();drawField();msg(t("التوقعات البحرية جاهزة","Prévisions marines prêtes"))}catch(e){console.error(e);msg(t("تعذر تحميل التوقعات","Impossible de charger les prévisions"))}}
function formatTime(v){if(!v)return "--";const d=new Date(v);return d.toLocaleTimeString(lang==="ar"?"ar-TN":"fr-FR",{hour:"2-digit",minute:"2-digit"})}
function setTime(i){timeIndex=+i||0;grid=currentGrid();document.getElementById("timeLabel").textContent=formatTime(forecast[0]?.times?.[timeIndex]);drawField()}
function togglePlay(){playing=!playing;document.getElementById("play").textContent=playing?"⏸":"▶";if(playing){clearInterval(playTimer);playTimer=setInterval(()=>{const max=+document.getElementById("time").max;if(timeIndex>=max){timeIndex=0}else timeIndex++;document.getElementById("time").value=timeIndex;setTime(timeIndex)},700)}else clearInterval(playTimer)}
function setMode(m){mode=m;document.querySelectorAll(".layers button[data-layer]").forEach(b=>b.classList.toggle("on",b.dataset.layer===m));if(m==="depth"){bathy.addTo(map);field.style.display="none";legend.textContent=t("📏 الأعماق — GEBCO 2026","📏 Profondeur — GEBCO 2026")}else{if(map.hasLayer(bathy))map.removeLayer(bathy);field.style.display="block";legend.textContent=m==="wind"?t("🌬️ الرياح — خريطة متحركة","🌬️ Vent — carte dynamique"):m==="waves"?t("🌊 الموج — اختر نقطة للتفاصيل","🌊 Vagues — touchez un point"):m==="current"?t("↗️ التيارات — السرعة والاتجاه","↗️ Courants — vitesse et direction"):t("🌡️ SST — حرارة سطح البحر","🌡️ SST — température de surface");drawField()}}
document.querySelectorAll(".layers button[data-layer]").forEach(b=>b.onclick=()=>setMode(b.dataset.layer));
document.getElementById("sat").onclick=()=>{if(map.hasLayer(sat)){map.removeLayer(sat);street.addTo(map)}else{map.removeLayer(street);sat.addTo(map)}};
document.getElementById("gps").onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{map.setView([p.coords.latitude,p.coords.longitude],12);select(p.coords.latitude,p.coords.longitude)},()=>msg(t("اسمح باستخدام GPS","Autorisez le GPS")));
function renderBeaches(){if(!window.beachLayer)window.beachLayer=L.layerGroup();window.beachLayer.clearLayers();for(const b of (window.PRO_BEACHES||[])){const mk=L.circleMarker([b[2],b[3]],{radius:5,weight:1,color:"#8be9fd",fillColor:"#0ea5e9",fillOpacity:.85});mk.bindTooltip(b[0],{direction:"top",offset:[0,-5]});mk.on("click",()=>select(b[2],b[3]));window.beachLayer.addLayer(mk)}}
function nearestBeach(lat,lon){let best=null,bd=1e9;for(const b of (window.PRO_BEACHES||[])){const d=Math.hypot((b[2]-lat)*111,(b[3]-lon)*111*Math.cos(lat*Math.PI/180));if(d<bd){bd=d;best=b}}return best?{b:best,d:bd}:null}
function moonInfo(lat,lon){if(!window.SunCalc)return "";const now=new Date(),i=SunCalc.getMoonIllumination(now),mt=SunCalc.getMoonTimes(now,lat,lon),icons=["🌑","🌒","🌓","🌔","🌕","🌖","🌗","🌘"];let n=Math.round(i.phase*8)%8,max={v:-99,t:null},min={v:99,t:null};for(let k=0;k<=144;k++){const d=new Date(now.getTime()+k*10*60000),v=SunCalc.getMoonPosition(d,lat,lon).altitude;if(v>max.v)max={v,t:d};if(v<min.v)min={v,t:d}}const f=d=>d?d.toLocaleTimeString(lang==="ar"?"ar-TN":"fr-FR",{hour:"2-digit",minute:"2-digit"}):"--";return t(icons[n]+" إضاءة "+Math.round(i.fraction*100)+"% • 🌙 "+f(max.t)+" • ☾ "+f(min.t),icons[n]+" "+Math.round(i.fraction*100)+"% • 🌙 "+f(max.t)+" • ☾ "+f(min.t))}async function select(lat,lon){
localStorage.setItem("pkf-current-location",JSON.stringify({lat:+lat.toFixed(5),lon:+lon.toFixed(5),updatedAt:Date.now()}));
if(marker)marker.remove(); marker=L.marker([lat,lon]).addTo(map).bindPopup("🎣 "+lat.toFixed(4)+", "+lon.toFixed(4)).openPopup();
point.hidden=false; const nb=nearestBeach(lat,lon); point.textContent="🎣 "+t("نقطة الصيد","Point de pêche")+": "+lat.toFixed(4)+", "+lon.toFixed(4)+(nb?" • 🏖️ "+nb.b[0]+" • "+nb.d.toFixed(1)+" km":"");
info.hidden=false;
info.innerHTML="<div class='marine-head'><b>🎣 "+t("بيانات نقطة الصيد","Données du point de pêche")+"</b><span>"+lat.toFixed(4)+", "+lon.toFixed(4)+"</span></div><div class='marine-grid'><div>🌬️<small>"+t("الرياح","Vent")+"</small><b id='miWind'>…</b></div><div>💨<small>"+t("هبات","Rafales")+"</small><b id='miGust'>…</b></div><div>🧭<small>"+t("اتجاه الرياح","Direction")+"</small><b id='miDir'>…</b></div><div>🌊<small>"+t("الموج","Vagues")+"</small><b id='miWave'>…</b></div><div>〰️<small>"+t("فترة الموج","Période")+"</small><b id='miPeriod'>…</b></div><div>↗️<small>"+t("التيار","Courant")+"</small><b id='miCurrent'>…</b></div><div>🌡️<small>SST</small><b id='miSst'>…</b></div><div>🌡️<small>"+t("حرارة الهواء","Air")+"</small><b id='miAir'>…</b></div></div><div class='marine-extra'><span>📏 "+t("العمق","Profondeur")+": <b id='miDepth'>…</b></span><span>🏖️ "+(nb?nb.b[0]:"—")+" <b>"+(nb?nb.d.toFixed(1)+" km":"")+"</b></span><span>🌙 <b id='miMoon'>…</b></span></div><div class='marine-actions'><button onclick='saveFavorite()'>⭐ "+t("حفظ النقطة","Enregistrer")+"</button><a href='planner.html'>🎣 "+t("مخطط الصيد","Planner")+"</a></div>";
const weatherUrl="https://api.open-meteo.com/v1/forecast?latitude="+lat+"&longitude="+lon+"&hourly=temperature_2m,wind_speed_10m,wind_gusts_10m,wind_direction_10m&forecast_days=2&timezone=auto";
const marineUrl="https://marine-api.open-meteo.com/v1/marine?latitude="+lat+"&longitude="+lon+"&hourly=wave_height,wave_period,wave_direction,sea_surface_temperature,ocean_current_velocity,ocean_current_direction&forecast_days=2&timezone=auto&cell_selection=sea";
try{const [wr,mr]=await Promise.all([fetch(weatherUrl).then(x=>x.json()),fetch(marineUrl).then(x=>x.json())]);const wi=Math.min(timeIndex,(wr.hourly?.time?.length||1)-1),mi=Math.min(timeIndex,(mr.hourly?.time?.length||1)-1);const val=(a,i)=>Number.isFinite(a?.[i])?a[i]:null;const fmt=(v,u="")=>v===null?"—":v.toFixed(1)+u;document.getElementById("miWind").textContent=fmt(val(wr.hourly?.wind_speed_10m,wi)," km/h");document.getElementById("miGust").textContent=fmt(val(wr.hourly?.wind_gusts_10m,wi)," km/h");const wd=val(wr.hourly?.wind_direction_10m,wi);document.getElementById("miDir").textContent=wd===null?"—":Math.round(wd)+"°";document.getElementById("miWave").textContent=fmt(val(mr.hourly?.wave_height,mi)," m");document.getElementById("miPeriod").textContent=fmt(val(mr.hourly?.wave_period,mi)," s");document.getElementById("miCurrent").textContent=fmt(val(mr.hourly?.ocean_current_velocity,mi)," m/s");document.getElementById("miSst").textContent=fmt(val(mr.hourly?.sea_surface_temperature,mi)," °C");document.getElementById("miAir").textContent=fmt(val(wr.hourly?.temperature_2m,wi)," °C")}catch(e){console.warn("point marine data",e)}
document.getElementById("miMoon").textContent=moonInfo(lat,lon)||"—";
if(mode==="depth"){try{const u="https://depth.opentopodata.org/v1/gebco2020/"+lat+","+lon;const d=await fetch(u).then(x=>x.json());const v=d.results?.[0]?.elevation;if(Number.isFinite(v))document.getElementById("miDepth").textContent=Math.abs(v).toFixed(1)+" m";else throw 0}catch(e){try{const b=map.getBounds(),s=map.getSize(),p=map.latLngToContainerPoint([lat,lon]),bbox=b.getSouth()+","+b.getWest()+","+b.getNorth()+","+b.getEast(),u="https://wms.gebco.net/mapserv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&LAYERS=gebco_latest_2&QUERY_LAYERS=gebco_latest_2&INFO_FORMAT=text/plain&CRS=EPSG:4326&BBOX="+bbox+"&WIDTH="+Math.round(s.x)+"&HEIGHT="+Math.round(s.y)+"&I="+Math.round(p.x)+"&J="+Math.round(p.y),txt=await fetch(u).then(x=>x.text()),match=txt.match(/-?\d+(?:\.\d+)?/);document.getElementById("miDepth").textContent=match?Math.abs(Number(match[0])).toFixed(1)+" m":"—"}catch(_){document.getElementById("miDepth").textContent="—"}}}else document.getElementById("miDepth").textContent=t("فعّل طبقة الأعماق ثم اضغط النقطة","Activez la couche profondeur puis touchez un point");
}
function showSheet(title,html){sheet.hidden=false;sheet.innerHTML="<button class='close' onclick='sheet.hidden=true'>✕</button><h3>"+title+"</h3>"+html}
function showBeaches(){const rows=(window.PRO_BEACHES||[]).map((b,i)=>"<div class='row' onclick='map.setView(["+b[2]+","+b[3]+"],12);select("+b[2]+","+b[3]+");sheet.hidden=true'><b>🏖️ "+b[0]+"</b><small>"+b[1]+" • "+b[2].toFixed(4)+", "+b[3].toFixed(4)+"</small></div>").join("");showSheet(t("شواطئ تونس","Plages de Tunisie"),rows)}
function speciesAdvice(x){const n=(x[0]+" "+x[1]).toLowerCase();let depth="10–40 m",season="ربيع • صيف • خريف",spot="حواف الصخور • القاع";if(/dorade|دوراد/.test(n)){depth="5–35 m";season="ربيع • صيف • خريف";spot="الصخور • الأعشاب • الرمل"}else if(/loup|bar|قاروص/.test(n)){depth="1–30 m";season="خريف • شتاء • ربيع";spot="الساحل الصخري • مصبات المياه"}else if(/thon|تونة|bonite|بونيط/.test(n)){depth="سطحي–50 m";season="صيف • خريف";spot="المياه المفتوحة • أسراب الطعم"}else if(/mérou|هامور|dentex|dentex|مرجان/.test(n)){depth="20–80 m";season="ربيع • صيف • خريف";spot="الصخور • القاع الصخري"}return {depth,season,spot}}
function showSpecies(){const rows=(window.PRO_SPECIES||[]).map((x,i)=>{const a=speciesAdvice(x);return "<div class='row species-row' onclick='showSpeciesDetail("+i+")'><b>🐟 "+(lang==="ar"?x[1]:x[0])+"</b><small>"+x[2]+" • "+a.depth+"</small></div>"}).join("");showSheet(t("دليل الأنواع","Guide des espèces"),rows)}
function showSpeciesDetail(i){const x=(window.PRO_SPECIES||[])[i];if(!x)return;const a=speciesAdvice(x);showSheet((lang==="ar"?x[1]:x[0]),"<div class='species-detail'><h3>🐟 "+(lang==="ar"?x[1]:x[0])+"</h3><p><b>"+t("الاسم العلمي","Nom scientifique")+"</b><br>"+x[2]+"</p><p><b>"+t("العمق المقترح","Profondeur indicative")+"</b><br>"+a.depth+"</p><p><b>"+t("الموسم التقريبي","Saison indicative")+"</b><br>"+a.season+"</p><p><b>"+t("أماكن محتملة","Habitat indicatif")+"</b><br>"+a.spot+"</p><small>"+t("هذه إرشادات عامة وليست ضمانًا لوجود السمك في النقطة.","Ces indications sont générales et ne garantissent pas la présence du poisson.")+"</small></div>")}
function saveFavorite(){if(!marker)return;const p=marker.getLatLng();favorites.push({lat:+p.lat.toFixed(5),lon:+p.lng.toFixed(5),name:"🎣 "+new Date().toLocaleString()});localStorage.setItem("pkf-favorites",JSON.stringify(favorites));msg(t("تم حفظ النقطة ⭐","Point enregistrée ⭐"))}
function showFavorites(){const rows=favorites.length?favorites.map((x,i)=>"<div class='row' onclick='map.setView(["+x.lat+","+x.lon+"],12);select("+x.lat+","+x.lon+");sheet.hidden=true'><b>"+x.name+"</b><small>"+x.lat+", "+x.lon+"</small></div>").join(""):"<div class='row'>"+t("لا توجد نقاط محفوظة","Aucun point enregistré")+"</div>";showSheet(t("النقاط المفضلة","Favoris"),rows)}
document.getElementById("beaches").onclick=showBeaches;document.getElementById("species").onclick=showSpecies;document.getElementById("favorites").onclick=()=>{if(marker)saveFavorite();else showFavorites()};document.getElementById("lang").onclick=()=>{lang=lang==="ar"?"fr":"ar";localStorage.setItem("pkf-lang",lang);document.documentElement.lang=lang;document.documentElement.dir=lang==="ar"?"rtl":"ltr";document.getElementById("lang").textContent=lang==="ar"?"FR":"AR";msg(lang==="ar"?"تم تغيير اللغة":"Langue changée")};
map.on("click",e=>select(e.latlng.lat,e.latlng.lng));document.getElementById("time").oninput=e=>setTime(e.target.value);document.getElementById("play").onclick=togglePlay;document.getElementById("beaches").onclick=()=>{renderBeaches();if(map.hasLayer(window.beachLayer)){map.removeLayer(window.beachLayer);document.getElementById("beaches").classList.remove("on")}else{window.beachLayer.addTo(map);document.getElementById("beaches").classList.add("on")}};map.on("move zoomend",drawField);addEventListener("resize",()=>{resizeField();seedParticles()});resizeField();seedParticles();loadForecast();setMode("wind");setInterval(()=>{if(mode==="wind"&&grid.length)drawField()},80);