const map=L.map("map",{zoomControl:false,preferCanvas:true}).setView([35.8,10.7],7);const street=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(map);const sat=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{attribution:"© Esri"});L.control.zoom({position:"bottomright"}).addTo(map);
const bathy=L.tileLayer.wms("https://wms.gebco.net/mapserv?",{layers:"gebco_latest_2",format:"image/png",transparent:true,version:"1.3.0",attribution:"Bathymetry © GEBCO"});let mode="wind",marker=null,points=[],timer=null;
const status=document.getElementById("status"),legend=document.getElementById("legend"),point=document.getElementById("point");
function msg(s){status.textContent=s}function color(mode,v){if(mode==="waves")return v<.5?"#5de4ff":v<1?"#22b4ff":v<1.5?"#ffcf4a":"#ff5c4d";if(mode==="current")return v<.15?"#75f0ff":v<.4?"#a675ff":"#ff65d1";return v<18?"#55e99a":v<30?"#ffd34e":"#ff5b4e"}
function paint(data){points.forEach(p=>p.remove());points=[];let vals=data.map(x=>mode==="waves"?x.wave:mode==="current"?x.cur:x.sst).filter(Number.isFinite);if(!vals.length)return;for(const x of data){const v=mode==="waves"?x.wave:mode==="current"?x.cur:x.sst;if(!Number.isFinite(v))continue;const c=L.circleMarker([x.lat,x.lon],{radius:7,color:"#fff",weight:1,fillColor:color(mode,v),fillOpacity:.72}).addTo(map);c.bindTooltip((mode==="waves"?"🌊 موج "+v.toFixed(2)+" m":mode==="current"?"↗️ تيار "+v.toFixed(2)+" km/h":"🌡️ SST "+v.toFixed(1)+" °C"),{direction:"top"});points.push(c)}legend.textContent=mode==="waves"?"🌊 طبقة الموج — بيانات Marine API":mode==="current"?"↗️ طبقة التيارات — السرعة الحالية": "🌡️ حرارة سطح البحر — SST"}
async function marineGrid(){const lats=[],lons=[];for(let lat=33.5;lat<=37.5;lat+=.5)for(let lon=7.5;lon<=11.5;lon+=.5){lats.push(lat.toFixed(2));lons.push(lon.toFixed(2))}const u="https://marine-api.open-meteo.com/v1/marine?latitude="+lats.join(",")+"&longitude="+lons.join(",")+"&current=wave_height,sea_surface_temperature,ocean_current_velocity&timezone=auto&cell_selection=sea";const r=await fetch(u).then(x=>x.json());const arr=Array.isArray(r)?r:[r];const out=[];for(let i=0;i<arr.length;i++){const q=arr[i],lat=Number(lats[i]),lon=Number(lons[i]);if(q?.current)out.push({lat,lon,wave:Number(q.current.wave_height),sst:Number(q.current.sea_surface_temperature),cur:Number(q.current.ocean_current_velocity)})}return out}
async function loadGrid(){try{msg("جاري تحميل طبقات البحر…");const d=await marineGrid();window.grid=d;paint(d);msg("تم تحميل "+d.length+" نقطة بحرية");}catch(e){msg("تعذر تحميل طبقات البحر")}}
function setMode(m){mode=m;document.querySelectorAll(".layers button[data-layer]").forEach(b=>b.classList.toggle("on",b.dataset.layer===m));if(m==="depth"){bathy.addTo(map);points.forEach(p=>p.remove());points=[];legend.textContent="📏 GEBCO bathymetry — اضغط على البحر لمحاولة قراءة العمق";msg("طبقة الأعماق من GEBCO")}else{if(map.hasLayer(bathy))map.removeLayer(bathy);if(window.grid)paint(window.grid);msg("طبقة "+m+" فعالة")}}
document.querySelectorAll(".layers button[data-layer]").forEach(b=>b.onclick=()=>setMode(b.dataset.layer));
document.getElementById("sat").onclick=()=>{if(map.hasLayer(sat)){map.removeLayer(sat);street.addTo(map)}else{map.removeLayer(street);sat.addTo(map)}};
document.getElementById("gps").onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{map.setView([p.coords.latitude,p.coords.longitude],12);select(p.coords.latitude,p.coords.longitude)},()=>msg("اسمح باستخدام GPS"));
async function select(lat,lon){if(marker)marker.remove();marker=L.marker([lat,lon]).addTo(map).bindPopup("🎣 نقطة الصيد<br>"+lat.toFixed(4)+", "+lon.toFixed(4)).openPopup();point.hidden=false;point.textContent="🎣 نقطة الصيد: "+lat.toFixed(4)+", "+lon.toFixed(4);if(mode==="depth"){try{const b=map.getBounds(),s=map.getSize(),p=map.latLngToContainerPoint([lat,lon]);const bbox=b.getSouth()+","+b.getWest()+","+b.getNorth()+","+b.getEast();const u="https://wms.gebco.net/mapserv?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetFeatureInfo&LAYERS=gebco_latest_2&QUERY_LAYERS=gebco_latest_2&INFO_FORMAT=text/plain&CRS=EPSG:4326&BBOX="+bbox+"&WIDTH="+s.x+"&HEIGHT="+s.y+"&I="+Math.round(p.x)+"&J="+Math.round(p.y);const t=await fetch(u).then(x=>x.text());point.textContent="📏 نتيجة GEBCO عند النقطة: "+t.replace(/\s+/g," ").slice(0,260)}catch(e){point.textContent="📏 لم يتمكن المصدر من إرجاع قيمة عمق لهذه النقطة."}}}
map.on("click",e=>select(e.latlng.lat,e.latlng.lng));loadGrid();setMode("wind");