const map=L.map("map",{zoomControl:false,preferCanvas:true}).setView([35.8,10.7],7);
const base=L.tileLayer("https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png",{attribution:"© OpenStreetMap"}).addTo(map);
const sat=L.tileLayer("https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}",{attribution:"© Esri"});
L.control.zoom({position:"bottomright"}).addTo(map);
const cv=document.getElementById("wind"),cx=cv.getContext("2d");let P=[],data=null,mark=null,layer="wind",timer=null;
function size(){cv.width=innerWidth*devicePixelRatio;cv.height=innerHeight*devicePixelRatio;cv.style.width=innerWidth+"px";cv.style.height=innerHeight+"px";cx.setTransform(devicePixelRatio,0,0,devicePixelRatio,0,0);map.invalidateSize({animate:false,pan:false})}
addEventListener("resize",size);addEventListener("orientationchange",()=>setTimeout(size,200));size();for(let i=0;i<220;i++)P.push({x:Math.random()*innerWidth,y:Math.random()*innerHeight});
function draw(i){cx.clearRect(0,0,innerWidth,innerHeight);if(!data)return;let s=data.wind_speed_10m?.[i]||10,d=(data.wind_direction_10m?.[i]||0)*Math.PI/180;if(layer!=="wind")return;cx.strokeStyle="rgba(97,221,255,.58)";for(const p of P){let dx=Math.sin(d)*(3+s*.12),dy=-Math.cos(d)*(3+s*.12);cx.beginPath();cx.moveTo(p.x,p.y);cx.lineTo(p.x+dx*2,p.y+dy*2);cx.stroke();p.x+=dx*.08;p.y+=dy*.08;if(p.x<0)p.x=innerWidth;if(p.x>innerWidth)p.x=0;if(p.y<0)p.y=innerHeight;if(p.y>innerHeight)p.y=0}requestAnimationFrame(()=>draw(i))}
async function load(lat,lon){if(mark)mark.remove();mark=L.marker([lat,lon]).addTo(map).bindPopup("🎣 نقطة الصيد").openPopup();document.getElementById("place").textContent=lat.toFixed(4)+", "+lon.toFixed(4);document.getElementById("msg").textContent="جاري تحميل البيانات...";
let w="https://api.open-meteo.com/v1/forecast?latitude="+lat+"&longitude="+lon+"&hourly=temperature_2m,pressure_msl,precipitation,wind_speed_10m,wind_gusts_10m,wind_direction_10m&forecast_days=7&timezone=auto";
let m="https://marine-api.open-meteo.com/v1/marine?latitude="+lat+"&longitude="+lon+"&hourly=wave_height,wave_direction,wave_period,sea_surface_temperature,ocean_current_velocity,ocean_current_direction&forecast_days=7&timezone=auto";
try{let[a,b]=await Promise.all([fetch(w).then(x=>x.json()),fetch(m).then(x=>x.json())]);data={...a.hourly,...b.hourly,time:a.hourly.time};let t=document.getElementById("time");t.max=data.time.length-1;t.value=0;render(0);document.getElementById("msg").textContent="بيانات حقيقية من Open-Meteo • اضغط طبقة ثم حرّك الزمن"}catch(e){document.getElementById("msg").textContent="تعذر تحميل البيانات"}} 
function render(i){if(!data)return;w.textContent=(data.wind_speed_10m?.[i]??"--")+" km/h";g.textContent=(data.wind_gusts_10m?.[i]??"--")+" km/h";wh.textContent=data.wave_height?.[i]==null?"--":data.wave_height[i].toFixed(2)+" m";sstv.textContent=data.sea_surface_temperature?.[i]==null?"--":data.sea_surface_temperature[i].toFixed(1)+" °C";clock.textContent=new Date(data.time[i]).toLocaleTimeString("ar-TN",{hour:"2-digit",minute:"2-digit"});let s=Math.max(0,Math.min(100,Math.round(100-Math.max(0,(data.wind_speed_10m?.[i]||0)-15)*2-Math.max(0,(data.wave_height?.[i]||0)-.7)*25)));score.textContent=s+"/100";bar.style.width=s+"%";draw(i)}
map.on("click",e=>load(e.latlng.lat,e.latlng.lng));document.getElementById("time").oninput=e=>render(+e.target.value);
document.getElementById("play").onclick=()=>{if(timer){clearInterval(timer);timer=null;play.textContent="▶";return}play.textContent="⏸";timer=setInterval(()=>{let t=document.getElementById("time"),v=+t.value+1;if(v>+t.max)v=0;t.value=v;render(v)},650)};
document.querySelectorAll("[data-layer]").forEach(b=>b.onclick=()=>{document.querySelectorAll("[data-layer]").forEach(x=>x.classList.remove("on"));b.classList.add("on");layer=b.dataset.layer;render(+(time.value||0));msg.textContent=layer==="depth"?"📏 الأعماق: مصدر bathymetry سيتم ربطه في مرحلة البيانات البحرية.":layer==="current"?"↗️ التيارات: بيانات السرعة/الاتجاه متاحة للنقطة المختارة.":layer==="waves"?"🌊 الأمواج: بيانات Marine API متاحة للنقطة المختارة.":layer==="sst"?"🌡️ SST: حرارة سطح البحر من Marine API.":"🌬️ الرياح المتحركة تعمل على الخريطة."});
gps.onclick=()=>navigator.geolocation?.getCurrentPosition(p=>{map.setView([p.coords.latitude,p.coords.longitude],12);load(p.coords.latitude,p.coords.longitude)},()=>alert("اسمح باستخدام GPS"));
sat.onclick=()=>{if(map.hasLayer(sat)){map.removeLayer(sat);base.addTo(map)}else{map.removeLayer(base);sat.addTo(map)}};
load(35.8,10.7);